FROM mongo

COPY ./volumes/equipe27_mongodb-data.tar.zst /tmp/

RUN apt-get update && \
    apt-get install -y zstd && \
    tar -I zstd -xf /tmp/equipe27_mongodb-data.tar.zst -C /data/db && \
    chown -R mongodb:mongodb /data/db

CMD ["mongod"]
