version: '3'
services:
  neo4j:
    build:
      context: .
      dockerfile: Dockerfile.neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_CREDENTIALS}
    networks:
      - mynetwork

  mongodb:
    build: 
      context: .
      dockerfile: Dockerfile.mongo 
    ports:
      - "27017:27017"
    networks:
      - mynetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - neo4j
      - mongodb

networks:
  mynetwork:
    driver: bridge


volumes:
  mongodb-data: